import json
import faiss
import numpy as np
import requests

from sentence_transformers import SentenceTransformer

#loading llm
def inference(prompt):
    r = requests.post("http://localhost:11434/api/generate", json={
        # "model": "deepseek-r1",
        "model": "llama3.1:latest",
        "prompt": prompt,
        "stream": False
    })

    response = r.json()
    print(response)
    return response



# ===========================
# Step 1 — Load FAISS Index
# ==============================

print("Loading FAISS index...")

index = faiss.read_index("vector_index.faiss")


# ==============================
# Step 2 — Load All Chunks
# ==============================

print("Loading chunks metadata...")

with open("all_chunks.json", "r", encoding="utf-8") as f:
    all_chunks = json.load(f)


# ==============================
# Step 3 — Load BGE-M3 Model
# ==============================

print("Loading embedding model...")

model = SentenceTransformer(
    "BAAI/bge-m3",
    device="cpu"
)


# ==============================
# Step 4 — Search Function
# ==============================

def filtered_search(query, k=20):

    # 🔥 BGE works better with instruction prefix
    query_for_embedding = (
        "Represent this question for searching: "
        + query
    )

    # Create embedding
    query_embedding = np.array(
        model.encode([query_for_embedding])
    ).astype("float32")

    # 🔥 Search more candidates (IMPORTANT FIX)
    D, I = index.search(query_embedding, k * 10)

    results = []

    query_lower = query.lower()

    want_imp = "imp" in query_lower
    want_pyq = "pyq" in query_lower
    want_syllabus = "syllabus" in query_lower

    for idx in I[0]:

        chunk = all_chunks[idx]

        meta = chunk["metadata"]

        # 🚫 Skip syllabus unless asked
        if not want_syllabus:
            if meta["type"] == "SYLLABUS":
                continue

        # Filter IMP
        if want_imp and meta["type"] != "IMP":
            continue

        # Filter PYQ
        if want_pyq and meta["type"] != "PYQ":
            continue

        results.append(chunk)

        if len(results) == k:
            break

    return results
# ==========================================
# llm process
# ===========================================


# ==============================
# Step 5 — Interactive Loop
# ==============================

if __name__ == "__main__":

    while True:

        user_query = input(
            "\nAsk something (or type exit): "
        )

        if user_query.lower() == "exit":
            break

        results = filtered_search(
            user_query,
            k=20
        )

        # print("\nResults:\n")
        # print(results)
        context_text = "\n\n".join(
        chunk["text"] for chunk in results
         )
        system_prompt = """
        You are an Exam Helper AI designed to generate textbook-style answers for syllabus-based subjects.

        Your responsibilities:

        1. Generate the main theoretical answer using your knowledge.
        2. Use the provided context ONLY to attach:
        - Previous Year Questions (PYQ)
        - Important Questions (IMP)
        - Syllabus topics

        3. If the question topic is outside the syllabus,
        respond:

        "This topic is not in the syllabus."

        -----------------------------------
        MARKS-BASED ANSWER RULES
        -----------------------------------

        If the user asks for:

        4 MARKS:
        Structure the answer as:
        - Definition
        - Advantages
        - Disadvantages

        6 MARKS:
        Structure the answer as:
        - Definition or Introduction
        - Explanation of key points
        - Diagram Explanation (if applicable)
        - Example (if applicable)

        If marks are not specified:
        Provide a standard structured explanation.

        -----------------------------------
        RAG CONTEXT USAGE RULE
        -----------------------------------

        The provided context contains:

        - PYQ (Previous Year Questions)
        - IMP (Important Questions)
        - SYLLABUS (Topic list)


        Use this context ONLY to append:

        PYQ Section  
        IMP Section  
        SYLLABUS Section  

        Do NOT copy theory answers from context.

        -----------------------------------
        SPECIAL QUERY HANDLING
        -----------------------------------

        If the user asks:

        "Give PYQ only"
        → Return only PYQ section

        "Give IMP only"
        → Return only IMP section

        "Give SYLLABUS"
        → Return only syllabus topics

        -----------------------------------
        OUTPUT FORMAT
        -----------------------------------

        Always structure output as:

        Main Answer:
        (Generated by LLM)

        PYQ:
        (list all pyq's from context if available)

        IMP:
        (list all imp's from context if available)

        SYLLABUS:
        (from context if available)

        Use headings and bullet points.
        Keep answers exam-ready.
        Avoid unnecessary explanations.

        """

        prompt = f"""

        SYSTEM:
        {system_prompt}

        -----------------------------------

        RAG CONTEXT:
        {context_text}

        -----------------------------------

        USER QUESTION:
        {user_query}

        -----------------------------------

        Generate the final answer.

        """

        response = inference(prompt)["response"]
        print(response)
       
            
            
            
#Prompt Process
